### ISSUE TITLE
可以检测到人脸，但是舵机并不随着人脸转动

### ISSUE THREAD

**Issue by guoyu666** [wtx666666/face-tracking-pan-tilt-camera#1]
你好，我测试的时候可以检测到人脸，但是舵机并没有随着人脸转动，请问是哪里出问题了呢？

**Comment by TianxingWu** [comment]
你好，这段描述过于宽泛了，不足以定位问题。建议先检查串口通信是否使用的端口是否正确。一个更详细的可供参考的解决思路已经通过邮箱发给你了。谢谢关注 :)

**Comment by Ca-lm** [comment]
你好   源码可以发我么

**Comment by Supreme-worker** [comment]
> 你好，我测试的时候可以检测到人脸，但是舵机并没有随着人脸转动，请问是哪里出问题了呢？



> 你好，我测试的时候可以检测到人脸，但是舵机并没有随着人脸转动，请问是哪里出问题了呢？

我也是这样，你解决了这个问题了吗

**Comment by Supreme-worker** [comment]
> 你好，这段描述过于宽泛了，不足以定位问题。建议先检查串口通信是否使用的端口是否正确。一个更详细的可供参考的解决思路已经通过邮箱发给你了。谢谢关注 :)

你好，能发我一份吗

**Comment by helloworld-y-y** [comment]
> 你好，这段描述过于宽泛了，不足以定位问题。建议先检查串口通信是否使用的端口是否正确。一个更详细的可供参考的解决思路已经通过邮箱发给你了。谢谢关注 :)

你好，可以也发我一份吗？

**Comment by XL1429** [comment]
请问 舵机跟STM32怎么接线呀？

**Comment by Joy2Boy** [comment]
> 你好，这段描述过于宽泛了，不足以定位问题。建议先检查串口通信是否使用的端口是否正确。一个更详细的可供参考的解决思路已经通过邮箱发给你了。谢谢关注 :)

你好，可以也发我一份吗
