### ISSUE TITLE
hex烧录进板子后 舵机疯狂抖动 并且COM口掉了

### ISSUE THREAD

**Issue by wubushanyan** [wtx666666/face-tracking-pan-tilt-camera#3]
### hex烧录进板子后 舵机疯狂抖动 并且COM口掉了  过一会串口连上 停止抖动 尝试运行py脚本获得如下报错，该报错在未识别人脸时正常，但是一旦识别出人脸就弹出改报错

**ERROR CODE**
![image](https://user-images.githubusercontent.com/56383722/163717276-602e8fb3-8c07-4907-a013-8b16bfdeea00.png)

ps:抖动的时候LED灯疯狂闪烁，知道电脑弹出连接设备的声音 大概是串口连上了就匀速闪烁了，测试了一下只要不将舵机信号线连接到PWM输出口就不会掉COM口，插上去立马就开始疯狂抖动

### 1.用的板子是STM32f103RCT6 连线如下 俩舵机MG90s接入5v gnd  黄色信号线接入输出PWM的PA6 PA7

![image](https://user-images.githubusercontent.com/56383722/163717406-652c9092-f01f-4a66-adfd-94956effcc14.png)

### 2.看了眼USART的位置也是PA9  PA10
![image](https://user-images.githubusercontent.com/56383722/163716033-3f6002d9-bd10-4cc6-8e4e-c0a5c888fb30.png)

### 查了参考手册发现TIM3和Keil里的代码设置的一样也是PA6  PA7
![image](https://user-images.githubusercontent.com/56383722/163716211-209d6035-d5b6-41da-b53b-08e2e850ccb2.png)
### 不过没看懂为啥代码里对TIM3的初始化这里使能的是GPIOB
![image](https://user-images.githubusercontent.com/56383722/163716377-74ffae45-2536-43ac-b138-2711766ef5cd.png)

其余均无修改，py发送坐标的方式也是 # 和 $ 没有改动serial 除了里面的闪烁灯我改为了PA8 只有这一个灯

请求指点，PID那块我大概理解了 是为了消除误差  主要是对电脑PYTHON 通过串口发送信息到STM32以及STM32识别这里有点小疑问

**Comment by wubushanyan** [comment]
我试了试不使用python进行串口通信 改用xcom，并且发送与初始值不一样的字符串
#320$400
舵机发生转动，但是XCOM提示串口掉了.
转动证明您写的recieveData();确实接收到了数据，但是从recieveData();开始到pid计算里面似乎有地方会让串口被占用？不懂，求指教 我是单片机小白
![0253FA5F](https://user-images.githubusercontent.com/56383722/163719710-f83f7d01-6e8f-4cd2-b498-a2958e8f6017.png)

**Comment by XL1429** [comment]
请问怎么生成hex文件

**Comment by wubushanyan** [comment]
> 请问怎么生成hex文件

用keil就行了

**Comment by XL1429** [comment]
现在主要不会用keil打开他给的代码，可以请教下您嘛





------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年6月10日(星期五) 晚上6:33
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [TianxingWu/face-tracking-pan-tilt-camera] hex烧录进板子后 舵机疯狂抖动 并且COM口掉了 (Issue #3)





  
请问怎么生成hex文件
  
用keil就行了

**Comment by Amylizhao** [comment]
最后有改好吗？不能正常运行啊 下载之后板子直接不亮了 com口掉了怎么解决的
